name: Check repositories compliance status

on:
  workflow_dispatch:  
jobs:
  check_compliance_status:
    runs-on: ubuntu-latest
    environment: terraform_main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Python installation
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      - name: Pyhthon dependencies installation
        run: |
          python -m pip install --upgrade pip
          pip install -r ./spyglass/requirements.txt

      - name: Run spyglass
        env:
            GH_APP_TOKEN: ${{ secrets.GH_APP_TOKEN }}
        run: |
           ls ./spyglass
           echo '```'>>$GITHUB_STEP_SUMMARY
           python ./spyglass/main.py >> $GITHUB_STEP_SUMMARY
           echo '```'>>$GITHUB_STEP_SUMMARY
